import { intro, outro, text, confirm, spinner } from '@clack/prompts';
import pc from 'picocolors';
import fs from 'fs-extra';
import path from 'path';
import { logger } from '../core/logger.js';

export async function initCommand() {
  intro(pc.bgCyan(pc.black(' next-kit ')));

  const projectName = await text({
    message: 'Project name?',
    placeholder: 'my-next-app',
    validate: (value) => {
      if (!value) return 'Project name is required';
      if (!/^[a-z0-9-]+$/.test(value)) return 'Use lowercase letters, numbers and hyphens only';
    },
  });

  if (typeof projectName === 'symbol') {
    logger.error('Operation cancelled');
    process.exit(0);
  }

  const useTailwind = await confirm({
    message: 'Use Tailwind CSS?',
    initialValue: true,
  });

  const useShadcn = await confirm({
    message: 'Include shadcn/ui setup?',
    initialValue: true,
  });

  const s = spinner();
  s.start('Creating project...');

  const projectPath = path.join(process.cwd(), projectName as string);

  // Create basic Next.js structure
  await fs.ensureDir(projectPath);
  await fs.ensureDir(path.join(projectPath, 'src/app'));
  await fs.ensureDir(path.join(projectPath, 'src/components'));

  // Create basic files
  await fs.writeJson(path.join(projectPath, 'package.json'), {
    name: projectName,
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'next lint',
    },
  }, { spaces: 2 });

  await fs.writeFile(
    path.join(projectPath, 'src/app/page.tsx'),
    `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to ${projectName}</h1>
    </main>
  );
}
`
  );

  await fs.writeFile(
    path.join(projectPath, 'src/app/layout.tsx'),
    `import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '${projectName}',
  description: 'Generated by next-kit',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`
  );

  s.stop('Project created successfully!');

  outro(pc.green(`Project "${projectName}" created. Run cd ${projectName} && npm install`));
}